default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000



test:
  <<: *default
  database: db/test.sqlite3


development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.db
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5